apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oeb2lpidv-java-quarkus 
  janus-idp.io/tekton: oeb2lpidv-java-quarkus
  backstage.io/kubernetes-id: oeb2lpidv-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oeb2lpidv-java-quarkus
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml